
create table if not EXISTS codemark (
                        id int8 generated by default as identity,
                        code varchar(255),
                        code_product varchar(255),
                        date_added date,
                        date_print date,
                        date_of_manufacture date,
                        date_out_oborot date,
                        date_v_oborot date,
                        filename varchar(255),
                        filename_added varchar(255),
                        is_oborot boolean,
                        is_out_oborot boolean,
                        is_print boolean, primary key (id)
);

create table if not EXISTS products (
                        id int8 generated by default as identity,
                        code_product varchar(255),
                        name varchar(255), primary key (id)
);

create table if not EXISTS users (
                    id int8 generated by default as identity,
                    login varchar(255),
                    name varchar(255),
                    password varchar(255), primary key (id)
);


alter table if exists codemark add constraint UK_mcu38fctn7uk0664io7v1mn61 unique (code);


